name: toolmetrics
on:
  workflow_dispatch:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  # workflow_dispatch:
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: peytonbrsmith/metrics@master
        with:
          # Your GitHub token
          filename: toolmetrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: no
          plugin_topics: yes
          plugin_topics_sort: stars    # Sort by most starred topics
          plugin_topics_mode: mastered # Display icons instead of labels
          plugin_topics_limit: 0       # Disable limitation
#           plugin_habits: yes
#           plugin_habits_charts: yes
#           config_timezone: America/Chicago
